import {
  FaFilePdf,
  FaDownload,
  FaShieldAlt,
  FaCheckCircle,
  FaExclamationTriangle,
} from "react-icons/fa";

function Report() {
  return (
    <div className="min-h-screen bg-slate-100 py-10 px-6">
      <div className="max-w-5xl mx-auto">

        <div className="bg-white rounded-3xl shadow-xl p-8">

          <div className="flex justify-between items-center mb-8">

            <div>
              <h1 className="text-4xl font-bold">
                AI Contract Report
              </h1>

              <p className="text-gray-500 mt-2">
                Generated by ContractGPT
              </p>
            </div>

            <button className="bg-blue-600 text-white px-6 py-3 rounded-xl flex items-center gap-3 hover:bg-blue-700">
              <FaDownload />
              Download PDF
            </button>

          </div>

          <div className="grid md:grid-cols-3 gap-6 mb-8">

            <div className="bg-green-50 rounded-xl p-6 text-center">

              <FaCheckCircle className="text-4xl text-green-600 mx-auto mb-3" />

              <h2 className="font-bold text-xl">
                Low Risk
              </h2>

            </div>

            <div className="bg-blue-50 rounded-xl p-6 text-center">

              <FaShieldAlt className="text-4xl text-blue-600 mx-auto mb-3" />

              <h2 className="font-bold text-xl">
                99% Confidence
              </h2>

            </div>

            <div className="bg-yellow-50 rounded-xl p-6 text-center">

              <FaExclamationTriangle className="text-4xl text-yellow-500 mx-auto mb-3" />

              <h2 className="font-bold text-xl">
                2 Clauses Need Review
              </h2>

            </div>

          </div>

          <div className="space-y-8">

            <div>

              <h2 className="text-2xl font-bold mb-3">
                Executive Summary
              </h2>

              <p className="text-gray-600 leading-8">
                This contract contains standard employment terms with a
                generally low risk profile. Two clauses require manual
                verification before signing.
              </p>

            </div>

            <div>

              <h2 className="text-2xl font-bold mb-3">
                Key Clauses
              </h2>

              <ul className="list-disc ml-8 space-y-3 text-gray-600">
                <li>Salary and Compensation</li>
                <li>Termination Conditions</li>
                <li>Confidentiality Clause</li>
                <li>Non-Disclosure Agreement</li>
                <li>Intellectual Property</li>
              </ul>

            </div>

            <div>

              <h2 className="text-2xl font-bold mb-3">
                AI Recommendations
              </h2>

              <div className="bg-yellow-50 border-l-4 border-yellow-500 p-5 rounded-lg">

                <p className="text-gray-700">
                  Review the termination clause and notice period before
                  signing the agreement.
                </p>

              </div>

            </div>

          </div>

          <div className="mt-10 flex items-center gap-3 text-gray-500">

            <FaFilePdf className="text-red-600 text-2xl" />

            Employment_Agreement_Report.pdf

          </div>

        </div>

      </div>
    </div>
  );
}

export default Report;